if-shell 'test -z "$SSH_CONNECTION"' \
	"set -g status-position top \; \
	set -g status-justify absolute-centre \; \
	set -g prefix C-SPACE \; \
	set -g default-shell /bin/zsh \; \
	bind f run-shell 'tmux neww ~/.config/tmux/tmux-session-dispensary.sh' \; \
	bind b set -g status"

set -a terminal-features "screen-256color:RGB"
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g status-style "bg=default"
set -g window-status-current-style "fg=default bold"
set -g status-right ""
set -g status-left "#S"

set -g mouse on

set -g allow-passthrough on
set -s set-clipboard on

bind r source-file "~/.config/tmux/tmux.conf"
bind G neww -n "lazygit" lazygit
bind E show-environment -g
